export {
	canCommit,
	canGlobal,
	canPublish,
	canShip,
	confirmNamedLine,
	globalInstallLine,
	globalWriteLabel,
	isNpmNotReadyReason,
	needsGlobal,
	npmNotReadyHint,
	npmNotReadyTitle,
	shipConfirmLine,
	commitCountLabel,
	fleetWriteIds,
	fleetWriteLabel,
	nextCutVersion,
	landPluginApplyOk,
	plainGitError,
	plainPluginError,
	plainPublishError,
	publishApplyTitle,
	publishResultLine,
	isGithubPublishReason,
	isPublishedReason,
	whyNotPublish,
	whyNotPush,
	writableCascadeCount,
} from '../../../src/lib/writeGate.js';
export type { FleetWriteId, GateGit, PublishGateRow } from '../../../src/lib/writeGate.js';
