export {
	canCommit,
	canCutVersion,
	commitCountLabel,
	fleetWriteIds,
	fleetWriteLabel,
	nextCutVersion,
	landPluginApplyOk,
	plainGitError,
	plainPluginError,
	plainPublishError,
	publishApplyTitle,
	publishResultLine,
	isGithubPublishReason,
	isPublishedReason,
	whyNotPublish,
	whyNotPush,
	writableCascadeCount,
} from '../../../src/lib/writeGate.js';
export type { FleetWriteId, GateGit, PublishGateRow } from '../../../src/lib/writeGate.js';
